---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-06-07 - 07:29:12 +0000
    app.quarkus.io/commit-id: cb920a5399594777b4ab13a1c33b71b3c55d73a0
  labels:
    app.kubernetes.io/name: quarkus-helloworld
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: quarkus-helloworld
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: quarkus-helloworld
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-06-07 - 07:29:12 +0000
    app.quarkus.io/commit-id: cb920a5399594777b4ab13a1c33b71b3c55d73a0
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: quarkus-helloworld
    app.kubernetes.io/managed-by: quarkus
  name: quarkus-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: quarkus-helloworld
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-06-07 - 07:29:12 +0000
        app.quarkus.io/commit-id: cb920a5399594777b4ab13a1c33b71b3c55d73a0
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: quarkus-helloworld
        app.kubernetes.io/managed-by: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: iocanel/quarkus-helloworld:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: quarkus-helloworld
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
